australian_list = [
  [ "Adelaide Airport", "ADL", "Adelaide" ],
  [ "Brisbane Airport", "BNE", "Brisbane" ],
  [ "Cairns Airport", "CNS", "Cairns" ],
  [ "Darwin International Airport", "DRW", "Darwin" ],
  [ "Melbourne Airport", "MEL", "Melbourne" ],
  [ "Perth Airport", "PER", "Perth" ],
  [ "Sydney Airport", "SYD", "Sydney" ],
  [ "Gold Coast Airport", "OOL", "Gold Coast" ],
  [ "Hobart International Airport", "HBA", "Hobart" ],
  [ "Port Hedland International Airport", "PHE", "Port Hedland" ],
  [ "Townsville International Airport", "TSV", "Townsville" ]
]

australian_list.each do |name, abbrev, city|
  Australian.create( name: name, abbrev: abbrev, city: city)
end


american_list = [
  ["Akron", "Akron Fulton International Airport", "CAK"],
  ["Albany", "Albany International Airport", "ALB"],
  ["Albuquerque", "Albuquerque International Airport", "ABQ"],
  ["Alexandria", "Alexandria International Airport", "AEX"],
  ["Alice", "Alice International Airport", "ALC"],
  ["Allentown", "Lehigh Valley International Airport", "LVI"],
  ["Anchorage", "Ted Stevens Anchorage International Airport", "ANC"],
  ["Atlanta", "HartsfielJackson Atlanta International Airport", "ATL"],
  ["Atlantic", "City Atlantic City International Airport", "ACY"],
  ["Austin", "AustiBergstrom International Airport", "AUS"],
  ["Bakersfield", "Meadows Field", "BFL"],
  ["Baltimore", "BaltimorWashington International Thurgood Marshall Airport", " "],
  ["Bangor", "Bangor International Airport", "BWI"],
  ["Bellingham", "Bellingham International Airport", "BLI"],
  ["Billings", "Billings Logan International Airport", "BIL"],
  ["Binghamton", "Greater Binghamton Airport", "BGM"],
  ["Birmingham", "BirminghaShuttlesworth International Airport", "BHX"],
  ["Boston", "Logan International Airport", "BOS"],
  ["Brownsville", "Brownsville/South Padre Island International Airport", "BRO"],
  ["Buffalo", "Buffalo Niagara International Airport", "BUF"],
  ["Burlington", "Burlington International Airport", "BTV"],
  ["Casper", "Casper/Natrona County International Airport", "CPR"],
  ["Charlotte", "Charlotte/Douglas International Airport", "CLT"],
  ["Charleston", "Charleston International Airport", "CHS"],
  ["Chicago", "O'Hare International Airport", "CHI"],
  ["Cincinnati", "Cincinnati/Northern Kentucky International Airport", "LUK"],
  ["Cleveland", "Cleveland Hopkins International Airport", "CLE"],
  ["Columbus", "Port Columbus International Airport, Rickenbacker International Airport", "CMH"],
  ["Corpus", "Christi Corpus Christi International Airport", "CRP"],
  ["Dallas/Fort Worth", "Dallas/Fort Worth International Airport", "DFW"],
  ["Dayton", "James M. Cox Dayton International Airport", "DAY"],
  ["Denver", "Denver International Airport", "DEN"],
  ["Des Moines", "Des Moines International Airport", "DSM"],
  ["Detroit", "Detroit Metropolitan Wayne County Airport", "DET"],
  ["Duluth", "Duluth International Airport", "DLH"],
  ["El Paso", "El Paso International Airport", "ELP"],
  ["Erie", "Erie International Airport", "ERI"],
  ["Fairbanks", "Fairbanks International Airport", "FAI"],
  ["Fargo", "Hector International Airport", "FAR"],
  ["Flint", "Bishop International Airport", "FNT"],
  ["Fort Lauderdale", "Fort LauderdalHollywood International Airport", "FLL"],
  ["Fort Myers", "Southwest Florida International Airport", "RSW"],
  ["Fort Wayne", "Fort Wayne International Airport", "FWA"],
  ["Fresno", "Fresno Yosemite International Airport", "FAT"],
  ["Glasgow", "Glasgow International Airport", "GGW"],
  ["Grand Rapids", "Gerald R. Ford International Airport", "GRR"],
  ["Great Falls", "Great Falls International Airport", "GTF"],
  ["Green Bay", "Austin Straubel International Airport", "GRB"],
  ["Greensboro", "Piedmont Triad International Airport", "GSO"],
  ["Greenville/Spartanburg", "GreenvillSpartanburg International Airport", "GSP"],
  ["Gulfport/Biloxi", "GulfporBiloxi International Airport", "GPT"],
  ["Harlingen", "Valley International Airport", "HRL"],
  ["Harrisburg/Middletown", "Harrisburg International Airport", "MDT"],
  ["Honolulu", "Honolulu International Airport", "HNL"],
  ["Houston", "George Bush Intercontinental Airport", "HOU"],
  ["Huntsville", "Huntsville International Airport", "HSV"],
  ["Indianapolis", "Indianapolis International Airport", "IND"],
  ["International Falls", "Falls International Airport", "INL"],
  ["Jackson", "JacksoEvers International Airport", "JAC"],
  ["Jacksonville", "Jacksonville International Airport", "JAX"],
  ["Juneau", "Juneau International Airport", "JNU"],
  ["Kalamazoo/Battle Creek", "Kalamazoo/Battle Creek International Airport", "AZO"],
  ["Kalispell", "Glacier Park International Airport", "FCA"],
  ["Kansas City", "Kansas City International Airport", "MCI"],
  ["Key West", "Key West International Airport", "EYW"],
  ["Ketchikan", "Ketchikan International Airport", "KTN"],
  ["Kona", "Kona International Airport", "KOA"],
  ["Lake Charles", "Chennault International Airport", "LCH"],
  ["Lansing", "Capital Region International Airport", "LAN"],
  ["Laredo", "Laredo International Airport", "LRD"],
  ["Las Vegas", "McCarran International Airport", "LAS"],
  ["Los Angeles", "Los Angeles International Airport", "LAX"],
  ["Louisville", "Louisville International Airport", "SDF"],
  ["Lubbock", "Lubbock Preston Smith International Airport", "LBB"],
  ["Marquette/Gwinn", "Sawyer International Airport", "MQT"],
  ["Massena", "Massena International Airport", "MSS"],
  ["McAllen", "McAlleMiller International Airport", "MFE"],
  ["Memphis", "Memphis International Airport", "MEM"],
  ["Miami", "Miami International Airport", "MIA"],
  ["Milwaukee", "General Mitchell International Airport", "MIL"],
  ["Minneapolis/Saint Paul", "MinneapoliSaint Paul International Airport", "MSP"],
  ["Missoula", "Missoula International Airport", "MSO"],
  ["Moses Lake", "Grant County International Airport", "MWH"],
  ["Myrtle Beach", "Myrtle Beach International Airport", "MYR"],
  ["Nashville", "Nashville International Airport", "BNA"],
  ["New Orleans", "Louis Armstrong New Orleans International Airport", "MSY"],
  ["New York City", "John F. Kennedy International Airport", "NYC"],
  ["Newark", "Newark Liberty International Airport", "EWR"],
  ["Newburgh", "Stewart International Airport", "SWF"],
  ["Newport", "News Newport News/Williamsburg International Airport", "PHF"],
  ["Niagara Falls", "New York Niagara Falls International Airport", "IAG"],
  ["Norfolk", "Norfolk International Airport", "ORF"],
  ["Oakland", "Metropolitan Oakland International Airport", "OAK"],
  ["Ogdensburg", "Ogdensburg International Airport", "OGS"],
  ["Palm Springs", "Palm Springs International Airport", "PSP"],
  ["Panama City", "Beach Northwest Florida Beaches International Airport", "ECP"],
  ["Pensacola", "Pensacola International Airport", "PNS"],
  ["Peoria", "General Wayne A. Downing Peoria International Airport", "PIA"],
  ["Philadelphia", "Philadelphia International Airport", "PHL"],
  ["Phoenix", "Phoenix Sky Harbor International Airport", "PHX"],
  ["Pittsburgh", "Pittsburgh International Airport", "PIT"],
  ["Plattsburgh", "Plattsburgh International Airport", "PBG"],
  ["Port Angeles", "William R. Fairchild International Airport", "CLM"],
  ["Portland", "Maine Portland International Jetport", "PWM"],
  ["Portland", "Oregon Portland International Airport", "PDX"],
  ["Portsmouth", "Portsmouth International Airport at Pease", "PSM"],
  ["Providence", "T.F. Green Airport", "PVD"],
  ["Raleigh", "RaleigDurham International Airport", "RDU"],
  ["Reno", "RenTahoe International Airport", "RNO"],
  ["Richmond", "Richmond International Airport", "RIC"],
  ["Rochester", "Minnesota Rochester International Airport", "ROC"],
  ["Sacramento", "Sacramento International Airport", "SAC"],
  ["Salt Lake City", "Salt Lake City International Airport", "SLC"],
  ["San Antonio", "San Antonio International Airport", "SAT"],
  ["San Diego", "San Diego International Airport", "SAN"],
  ["San Francisco", "San Francisco International Airport", "SFO"],
  ["San Jose", "San Jose International Airport", "SJO"],
  ["Santa Ana/Orange County", "John Wayne Airport", "SNA"],
  ["Sarasota\Bradenton", "SarasotBradenton International Airport", "SRQ"],
  ["Sault Ste.", "Marie Chippewa County International Airport", "SSM"],
  ["Savannah", "Savannah/Hilton Head International Airport", "SAV"],
  ["Seattle", "SeattlTacoma International Airport", "SEA"],
  ["Spokane", "Spokane International Airport", "GEG"],
  ["St. Petersburg", "St. PetersburClearwater International Airport", "PIE"],
  ["Syracuse", "Syracuse Hancock International Airport", "SYR"],
  ["Tampa", "Tampa International Airport", "TPA"],
  ["Toledo", "Toledo Express Airport", "TOL"],
  ["Tucson", "Tucson International Airport", "TUS"],
  ["Tulsa", "Tulsa International Airport", "TUL"],
  ["Washington", "D.C. Washington Dulles International Airport", "WAS"],
  ["Watertown", "Watertown International Airport", "ART"],
  ["West Palm Beach", "Palm Beach International Airport", "PBI"],
  ["WilkeBarre/Scranton", "WilkeBarre/Scranton International Airport", "AVP"],
  ["Wilmington", "Wilmington International Airport", "ILM"],
  ["Windsor", "Locks Bradley International Airport", "YQG"],
  ["Yuma", "Yuma International Airport", "YUM"]

]

american_list.each do |city, name, abbrev|
  American.create( city: city, name: name, abbrev: abbrev)
end
